name: on-push

on: [push]

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu]
        python: [3.6, 3.7, 3.8, 3.9]
        eccodes: [0]
        include:
          - os: macos
            python: 3.8
          - os: windows
            python: 3.7
          - os: ubuntu
            python: 3.9
            eccodes: 1

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python }}
        activate-environment: ${{ matrix.os }}-${{ matrix.python }}
        environment-file: tests/environment-${{ matrix.os }}-${{ matrix.python }}.yml
    - name: Install package
      shell: bash -l {0}
      run: |
        python -m pip install -e .
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        conda install pytest pytest-cov
        CFGRIB_USE_EXTERNAL_ECCODES_BINDINGS=${{ matrix.eccodes }} pytest -v --doctest-glob="*.rst" --cov=. --cov-report=xml --cov-branch .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

  code-quality:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        $CONDA/bin/conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  code-style:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Check code style with black
      run: |
        $CONDA/bin/conda install black
        $CONDA/bin/black --check .
    - name: Check code style with isort
      run: |
        $CONDA/bin/conda install isort
        $CONDA/bin/isort --check .
