name: on-push

on: [push]

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu]
        python: [3.6, 3.7, 3.8]
        extras: ['']
        include:
          - os: macos
            python: 3.8
          - os: ubuntu
            python: 3.8
            extras: -minimal
# python-eccodes and cffi both fail
#          - os: windows
#            python: 3.8

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python }}
        activate-environment: ${{ matrix.os }}-${{ matrix.python }}${{ matrix.extras }}
        environment-file: tests/environment-${{ matrix.os }}-${{ matrix.python }}${{ matrix.extras }}.yml
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        conda install pytest pytest-cov
        pip install --no-deps -e .
        pytest -v --cov=. --cov-report=xml .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8
        activate-environment: ubuntu-3.8
        environment-file: tests/environment-ubuntu-3.8.yml
    - name: Build documentation with Sphinx
      shell: bash -l {0}
      run: |
        conda install sphinx
        pip install --no-deps -e .
        python setup.py build_sphinx
    - name: Test README with pytest
      shell: bash -l {0}
      run: |
        conda install pytest pytest-cov
        pytest -v --cov=. --cov-report=xml README.rst

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        $CONDA/bin/conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  code-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check code style with black
      run: |
        $CONDA/bin/conda install black
        $CONDA/bin/black --check .
    - name: Check code style with isort
      run: |
        $CONDA/bin/conda install isort
        $CONDA/bin/isort --check .

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check MANIFEST.in
      run: |
        $CONDA/bin/conda install -c conda-forge check-manifest
        $CONDA/bin/check-manifest .
    - name: Build distributions
      run: |
        $CONDA/bin/conda install pip setuptools wheel
        $CONDA/bin/python setup.py sdist bdist_wheel
